export const MAKE_REQUEST='MAKE_REQUEST'
export const FAIL_REQUEST='FAIL_REQUEST'
export const GET_USER_LIST='getUsers'
export const DELETE_USER='deleteUser' 
export const ADD_USER='createUser'
export const UPDATE_USER='updateUser'  
export const GET_USER_OBJ='  getUser '